version: '3.9'

# Common environment variables for the indexer
x-indexer-environment: &indexer-environment
  POSTGRES_DIALECT: ${POSTGRES_DIALECT:-postgresql+asyncpg}  # SQLAlchemy dialect for PostgreSQL
  POSTGRES_HOST: postgres  # Hostname for the PostgreSQL server
  POSTGRES_PORT: 5432  # Port number for the PostgreSQL server
  POSTGRES_USER: postgres  # Username for PostgreSQL
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password  # File containing the PostgreSQL password
  POSTGRES_DBNAME: ton_index  # Name of the PostgreSQL database
  POSTGRES_DBROOT: /tondb  # Root directory for the PostgreSQL database

services:
  index-worker:
    build:
      context: ton-index-cpp  # Build context for the index worker service
      dockerfile: Dockerfile  # Dockerfile to use for building the index worker service
    secrets:
      - postgres_password  # Secret for PostgreSQL password
    volumes:
      - /var/ton-work/db:/tondb  # Volume for the worker database root
      # - /zpool/ton-work/db:/tondb  # (Optional) Alternate volume path
      # - /zpool/ton-work-testnet/db:/tondb  # (Optional) Testnet volume path
    environment: *indexer-environment  # Set environment variables for the index worker service
    deploy:
      mode: replicated  # Deployment mode for the service
      replicas: 1  # Number of replicas for the service
      placement:
        constraints:
          - "node.labels.${TONCENTER_ENV:?}.indexer-cpp.worker==true"  # Constraint to place the service on specific nodes
    networks:
      internal:  # Connect to the internal network
    command: --from ${TON_WORKER_FROM:-1}  # Command to start the index worker service
    restart: unless-stopped  # Restart the service unless it is stopped

networks:
  internal:
    attachable: true  # Allow attaching other services to this network
    external: false  # Define the internal network as non-external
    driver_opts:
      com.docker.network.driver.mtu: 1350  # Set MTU for the network driver

secrets:
  postgres_password:
    file: ${POSTGRES_PASSWORD_FILE:-private/postgres_password}  # Define the secret file for PostgreSQL password
